# Generated by Django 5.0.2 on 2024-03-01 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_currency_product_productsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Варианты название',
                'verbose_name_plural': 'Варианты название',
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.option', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Значение варианты',
                'verbose_name_plural': 'Значение варианты',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='Цвет')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.optionvalue', verbose_name='Варианты')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Вариант продукта',
                'verbose_name_plural': 'Варианты продукты',
            },
        ),
    ]
