# Generated by Django 5.0.2 on 2024-03-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_option_optionvalue_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='sell_price',
        ),
    ]
